name: funx
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/makjac/funx

environment:
  sdk: ^3.9.2

dev_dependencies:
  test: ^1.25.6
  very_good_analysis: ^10.0.0
