name: funx
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
# dependencies:
# path: ^1.9.0

dev_dependencies:
  test: ^1.25.6
  very_good_analysis: ^10.0.0
