name: funx
description: Composable function decorators for advanced execution control and reliability.
version: 1.2.1
repository: https://github.com/makjac/funx

environment:
  sdk: ^3.9.2

dev_dependencies:
  test: ^1.25.6
  very_good_analysis: ^10.0.0
